### PR TITLE
add pagination to api-analytics graphs

### PR DESCRIPTION
**Pull request by anthonyettinger**
add pagination to api-analytics graphs

- add prev/next buttons

@jtary PTAL

### CODE REVIEW

**Comment by anthonyettinger** [comment]
waiting for @altsang to review

**Comment by anthonyettinger** [comment]
test please

**Comment by jtary** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by rmg** [comment]
@slnode test please

**Pull request merged**
