### PR TITLE
Revive protractor tests

### PR DESCRIPTION
**Pull request by rmg**
* [x] passing locally on OS X
* [x] passing on CI

Connect to strongloop-internal/scrum-nodeops#457

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by seanbrookes** [comment]
LGTM

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
Passing on CI: http://ci.strongloop.com/job/strong-arc.pr/949/

**Pull request merged**
