### PR TITLE
Hide app-controller when not supported

### PR DESCRIPTION
**Pull request by jtary**
Hide the app controller from the nav menu when running Arc outside of a
project directory.

connect to #925

### CODE REVIEW

**Comment by seanbrookes** [comment]
not sure this is needed as the App Controller is going to change next sprint to a more basic 'node start' type of implementation which technically should work outside a LB context

**Comment by jtary** [comment]
Still think this would be needed. While you could technically click to startup the PM, it wouldn't actually be starting any application unless you were in a project directory. Seems to be like it would be less confusing to simply hide the control unless you have some sort of application context.

**Comment by jtary** [comment]
test please

**Comment by jtary** [comment]
test please

**Comment by seanbrookes** [comment]
Maybe I'm missing something but I'm not sure this logic is quite correct.  

It looks like if we find the build-deploy app we will show the App Controller but if I'm not mistaken there are cases where a user could be in a 'non-LB' oriented node app that could still be a valid node project that Arc can trigger a start on

**Comment by seanbrookes** [comment]
test please

**Comment by seanbrookes** [comment]
given the discussion around short term priorities the LGTM

**Comment by jtary** [comment]
@slnode test please

**Comment by jtary** [comment]
test please

**Pull request merged**
