### PR TITLE
add clientDetail to popover on endpoint chart

### PR DESCRIPTION
**Pull request by chovy**
add clientDetail to popover on endpoint chart

@seanbrookes PLTA

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by anthonyettinger** [comment]
test please

**Comment by seanbrookes** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
