### PR TITLE
fix pm host error bug on process manager

### PR DESCRIPTION
**Pull request by anthonyettinger**
@seanbrookes PTAL

### CODE REVIEW

**Comment by seanbrookes** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by rmg** [comment]
Failing on CI because this branch is out of date. It should be rebased on master so that it includes the fixes from #1532

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by rmg** [comment]
Only failures on CI are the existing failures on Windows. LGTM as-is.

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
