### PR TITLE
fix alignment on button for app popover

### PR DESCRIPTION
**Pull request by anthonyettinger**
#1577 

@jtary PTAL

### CODE REVIEW

**Comment by rmg** [comment]
Build is failing due to lint:
```
build-tasks/download-help-assets.js
  line 42  col 11  'msg' is already defined.
```

**Comment by jtary** [comment]
Change LGTM, but should fix the linting issue before merging.

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
@rmg not sure what the issue is. i fixed the linter problem about `var msg` being declared twice.

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by cgole** [comment]
test please

**Pull request merged**
