### PR TITLE
use standard error color on composer model name

### PR DESCRIPTION
**Pull request by anthonyettinger**
- change to use new error message color defined in styleguide

### CODE REVIEW

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
@seanbrookes please review

**Comment by anthonyettinger** [comment]
test please

**Comment by seanbrookes** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
