### PR TITLE
fix hilighting on selected project

### PR DESCRIPTION
**Pull request by anthonyettinger**
fix hilighting on selected project

### CODE REVIEW

**Comment by anthonyettinger** [comment]
@jtary PTAL

**Comment by jtary** [comment]
@anthonyettinger LGTM

**Comment by rmg** [comment]
```
[20:23:06] 'test-client-integration' errored after 8.01 s
[20:23:06] Error: Failed with exit code 1
    at ChildProcess.<anonymous> (/mnt/jenkins/workspace/strong-arc/1de32925/gulpfile.js:316:16)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
[20:23:06] 'test' errored after 12 s
[20:23:06] Error in plugin 'run-sequence'
Message:
    An error occured in task 'test-client-integration'.
npm ERR! Test failed.  See above for more details.
```

**Comment by anthonyettinger** [comment]
test please

**Comment by rmg** [comment]
@slnode test please

**Pull request merged**
