### PR TITLE
Fix/410 final pm selector consolidation

### PR DESCRIPTION
**Pull request by seanbrookes**
replace tracing pm host selector with the common one used elsewhere

- added the ability to inject the process collection into the comopnent so the hosting module (tracing) can process the processes based on whether they are tracing or not and override the collection in the process display.

connected to: strongloop-internal/scrum-loopback#410

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by seanbrookes** [comment]
test please

**Comment by anthonyettinger** [comment]
LGTM

**Pull request merged**
