### PR TITLE
convert links in profiler to spans

### PR DESCRIPTION
**Pull request by anthonyettinger**
- the links to files are broken because we don't have a file on the file system to link to
- make them spans instead
- change link styling to look like a span

#1028

### CODE REVIEW

**Comment by anthonyettinger** [comment]
@seanbrookes PTAL

**Comment by anthonyettinger** [comment]
test please

**Comment by rmg** [comment]
@slnode test please

**Comment by anthonyettinger** [comment]
test please

**Comment by seanbrookes** [comment]
LGTM

**Pull request merged**
