### PR TITLE
revert d3 library upgrades

### PR DESCRIPTION
**Pull request by anthonyettinger**
- try to fix layout issues with metrics Dennis is experiencing

#1521

### CODE REVIEW

**Comment by anthonyettinger** [comment]
@seanbrookes PTAL

**Comment by seanbrookes** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by seanbrookes** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by rmg** [comment]
@slnode test please

**Comment by seanbrookes** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by rmg** [comment]
@slnode test please

**Pull request merged**
