### PR TITLE
api metrics

### PR DESCRIPTION
**Pull request by anthonyettinger**
add api metrics

### CODE REVIEW

**Comment by anthonyettinger** [comment]
@jtary PTAL

**Comment by anthonyettinger** [comment]
test please

**Comment by jtary** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
