### PR TITLE
Sl deploy accept size

### PR DESCRIPTION
**Pull request by Setogit**
connect to #582

### CODE REVIEW

**Comment by Setogit** [comment]
Reverted the revert of 3a2210a

**Comment by seanbrookes** [comment]
Not really sure what I'm reviewing here.  There are 117 changed files in this PR.

**Comment by seanbrookes** [comment]
the changes look good to me but it looks like the branch may be messed up (with gateway maybe?).  That should be looked at before merging and the build failure (of course)

**Comment by Setogit** [comment]
@slnode test please

**Comment by rmg** [comment]
commit statuses appear out of sync. The build was successful: http://ci.strongloop.com/job/strong-arc.pr/39/

**Comment by rmg** [comment]
For posterity, this was merged but I force push un-merged it due to the extraneous commits that were pulled in. Replacement is #1546.

**Pull request merged**
