### PR TITLE
fix property menu when navigating back and forth in composer

### LINKED ISSUE #1568: Composer: scaffolded model, data type does not show up
steps to reproduce:

1. `slc loopback` a new project
2. `slc loopback:model` a new model
3. give model properties
4. `slc arc`

model doesn't have dropped down values for data types properly displayed

image

### PR DESCRIPTION
**Pull request by anthonyettinger**
- property type menu now shows properly selected property

fixes #1568 
@jtary PTAL

### CODE REVIEW

**Comment by jtary** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
