### PR TITLE
Auto add entry for localhost PM

### PR DESCRIPTION
**Pull request by jtary**
Automatically add an entry for the locally running PM to the PM manager
list.

connect to #1185

### CODE REVIEW

**Comment by anthonyettinger** [comment]
LGTM

**Comment by anthonyettinger** [comment]
wrong ticket. sorry

**Comment by bajtos** [comment]
This looks like a forgotten and abandoned pull request to me. Is it still relevant? Shall we close it?

**Comment by seanbrookes** [comment]
We shouldn't close this as it may still happen as part of the strong-pm evolution within Arc

**Pull request closed without merging**
