### PR TITLE
remove react from arc-user directive

### PR DESCRIPTION
**Pull request by anthonyettinger**
- login page

### CODE REVIEW

**Comment by anthonyettinger** [comment]
@jtary PTAL

**Comment by rmg** [comment]
As a general comment, about half of the changes seem to be whitespace or formatting only and unrelated to the described change. Ideally this PR would have been 2 commits instead of 1.

**Comment by anthonyettinger** [comment]
@rmg -- whats the point of doing 2 commits if I squash them down to one?

**Comment by rmg** [comment]
@anthonyettinger you wouldn't squash them down to one commit.

**Comment by anthonyettinger** [comment]
Connects to strongloop-internal/scrum-arc/30

**Comment by jtary** [comment]
@anthonyettinger LGTM

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
