### PR TITLE
WIP arc traces implementation

### PR DESCRIPTION
**Pull request by sam-github**
Implemented in this branch:
- connected to strongloop/strong-arc#1153
- connected to strongloop-internal/scrum-nodeops#475

### CODE REVIEW

**Comment by chandadharap** [comment]
Do not merge before an interim Arc release.

**Comment by seanbrookes** [comment]
test please

**Comment by anthonyettinger** [comment]
LGTM

**Comment by seanbrookes** [comment]
test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by seanbrookes** [comment]
test please

**Comment by rmg** [comment]
@slnode test please

**Comment by seanbrookes** [comment]
test please

**Comment by seanbrookes** [comment]
@slnode test please

**Pull request merged**
