### PR TITLE
make changes in for PM

### PR DESCRIPTION
**Pull request by anthonyettinger**
- Process label should be `Count` and 'PIDs`
- Load Balancer should be right aligned with end of the table
- The Count spinner should be disabled in the Problem state
- Spacing: please put more spacing between the header and the start of the

### CODE REVIEW

**Comment by anthonyettinger** [comment]
@seanbrookes

**Comment by seanbrookes** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
@seanbrookes a few more commits while waiting for builds

**Pull request merged**
