### PR TITLE
remove tracing feature flag

### PR DESCRIPTION
**Pull request by seanbrookes**
connected to strongloop-internal/scrum-nodeops#721

### CODE REVIEW

**Comment by jtary** [comment]
LGTM

**Comment by chandadharap** [comment]
This assumes that Smart Profiling and Tracing are releasing at the same time?

**Comment by jtary** [comment]
It does seem to do that, @seanbrookes was that not the intention?

**Comment by chandadharap** [comment]
Be prepared to cherry pick that @seanbrookes in case Smart Profiling does not finish QA. Tracing launches next week Tuesday.

**Comment by seanbrookes** [comment]
ok I'll put together a list of pr's to cherry pick if we need to.

**Pull request merged**
