### PR TITLE
add validation to "add host" form

### PR DESCRIPTION
**Pull request by anthonyettinger**
add validation to "add host" form

- form name for host was colliding with port field

@seanbrookes

### CODE REVIEW

**Comment by anthonyettinger** [comment]
test please

**Comment by seanbrookes** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
