### PR TITLE
Update README for strong-pm.io

### PR DESCRIPTION
**Pull request by sam-github**
[README](https://github.com/strongloop/strong-arc/blob/readme-update/README.md).

Connect to strongloop/strongloop#191

### CODE REVIEW

**Comment by sam-github** [comment]
Above makes arc readme more consistent with other projects, OK?

**Comment by chandadharap** [comment]
LGTM

**Comment by altsang** [comment]
the descriptor for strong-arc is to narrow IMHO - "GUI for StrongLoop Process Manager", "strong-pm" and "LoopBack framework", it's also inconsistent - why omit "GUI for StrongLoop Profiler" for example

would like @ijroth and Juan Carlos to weigh in, my preference would be to keep a generic description and and a bulleted list of modules and descriptions

**Comment by sam-github** [comment]
@altsang I'll leave this README alone, other than the minimal reference to strong-pm.io: b9ca503

I suspect that our github READMEs aren't well travelled landing pages, there may be no need to update this further.

Note that the README dates from Arc's days when it was only a UI for generator-loopback, and likely predates loopback.io: you may wish to just delete the loopback scaffolding getting started and insert a link to loopback.io.

**Pull request closed without merging**
