### PR TITLE
change wording on deploy success message

### PR DESCRIPTION
**Pull request by anthonyettinger**
- change wording to reflect deploy has started but not finished.

### CODE REVIEW

**Comment by anthonyettinger** [comment]
@seanbrookes please review

**Comment by anthonyettinger** [comment]
test please

**Comment by seanbrookes** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
