### PR TITLE
cleanup header and navbar

### PR DESCRIPTION
**Pull request by anthonyettinger**
- add new icons
- resize icons
- fixing spacing issues
- adjust dynamic menu positioning

@seanbrookes

### CODE REVIEW

**Comment by seanbrookes** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
#898

**Comment by altsang** [comment]
@stacy-hunt can you review and verify please? thx

**Comment by stacy-hunt** [comment]
Yep!

**Pull request merged**
