### PR TITLE
add favicon.ico to Arc's root static path

### PR DESCRIPTION
**Pull request by rmg**
Will get rid of the browser console errors about not finding it and
give Arc tabs a default icon.

@altsang was missing intentionally, waiting for a custom Arc icon?

### CODE REVIEW

**Comment by altsang** [comment]
Not sure actually.  Was going to ask about favicon yesterday actually, but got diverted

@seanbrookes - do you remember?

**Comment by seanbrookes** [comment]
can't recal, but please don't make it this one:
image

it looks more limp than an arc

**Comment by rmg** [comment]
@seanbrookes this is a PR that just adds the 16x16 favicon.ico that is used in LoopBack apps by default and on strongloop.com

**Comment by seanbrookes** [comment]
LGTM

**Comment by altsang** [comment]
will create a story to get a replacement icon

**Comment by altsang** [comment]
https://github.com/strongloop/strong-arc/issues/1358

**Pull request merged**
