### PR TITLE
Update package metadata

### PR DESCRIPTION
**Pull request by rmg**
Make package.json more npm compliant:
* update license field to SPDX expression
* add bugs property

Connect to strongloop-internal/scrum-nodeops#642

### CODE REVIEW

**Comment by sam-github** [comment]
LGTM

**Comment by sam-github** [comment]
@rmg I merged, save you the trouble.

**Comment by rmg** [comment]
@sam-github thanks, I've been neglecting my notifications all afternoon.

**Comment by sam-github** [comment]
No implications of neglect, I just didn't think this PR needed further deliberation on anyone's part.

**Pull request merged**
