### PR TITLE
change folder navigation to breadcrumbs

### PR DESCRIPTION
**Pull request by anthonyettinger**
- remove dropdown folder navigation in file picker
- add breadcrumbs
- add placeholder icon for path separator

### CODE REVIEW

**Comment by anthonyettinger** [comment]
@jtary PTAL

**Comment by anthonyettinger** [comment]
test please

**Comment by jtary** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
