### PR TITLE
removed react depedency from metrics module

### PR DESCRIPTION
**Pull request by jtary**
Replaced metrics-ticker implementation with Angular templates instead of React, and removed metrics.react.js.

connect to strongloop-internal/scrum-arc#35

### CODE REVIEW

**Comment by jtary** [comment]
test please

**Comment by jtary** [comment]
@slnode test please

**Comment by jtary** [comment]
@slnode test please

**Comment by jtary** [comment]
@slnode test please

**Comment by jtary** [comment]
@slnode test please

**Comment by jtary** [comment]
@slnode test please

**Comment by jtary** [comment]
PTAL

**Comment by anthonyettinger** [comment]
LGTM

**Pull request merged**
