### PR TITLE
upgrade to ws@0.8.0

### PR DESCRIPTION
**Pull request by rmg**
ws@0.8.0 comes with improved support for iojs-v3

Also did a bunch of unrelated work on the protractor tests which should help with their stability.

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by anthonyettinger** [comment]
LGTM

**Comment by rmg** [comment]
As a bonus I threw in code coverage reporting for the karma tests.

**Pull request merged**
