### PR TITLE
Fix squashed  / overlapping chart containers

### PR DESCRIPTION
**Pull request by seanbrookes**
- removed the css tables containers so they stack neatly now

connected to: #1564

### CODE REVIEW

**Comment by anthonyettinger** [comment]
LGTM

**Comment by seanbrookes** [comment]
test please

**Comment by seanbrookes** [comment]
test please

**Comment by seanbrookes** [comment]
slnode test please

**Comment by anthonyettinger** [comment]
test please

**Comment by seanbrookes** [comment]
test please

**Pull request merged**
