### PR TITLE
clean vendor directory before running build and bower install

### PR DESCRIPTION
**Pull request by anthonyettinger**
clean vendor directory before running build and bower install

- clean vendor
- bower install
- gulp build

### CODE REVIEW

**Comment by anthonyettinger** [comment]
@seanbrookes 
@jtary

**Comment by jtary** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by rmg** [comment]
You forgot to move the gulp devDependencies to regular dependencies, now `npm install strongloop` is broken.

**Pull request merged**
