### PR TITLE
update d3 libs

### PR DESCRIPTION
**Pull request by anthonyettinger**
update all d3-related packages

### CODE REVIEW

**Comment by anthonyettinger** [comment]
@jtary PTAL

**Comment by jtary** [comment]
LGTM

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by anthonyettinger** [comment]
test please

**Comment by rmg** [comment]
The only failures are some connectivity issues within the CI cluster. I think you're safe to merge this.

**Pull request merged**
