### PR TITLE
Fix #1085 - styleguide align fix

### LINKED ISSUE #1085: styleguide retrofit: alignment is off after text input retrofit
As an Arc user I'm looking for consistency of alignment because it makes for a product to feel polished.

Composer: `Is Id`, `Required` and `Index` labels and checkboxes seems to be aligned differently.

image

Build and Deploy: labels on top of input field boxes are flush with input field on the left, but I believe they should be slightly indented as in the Composer? or maybe the other way around?

image

Process Manager: `Load Balancer` link button is not aligned when no row is present

image

after row insertion the `Load Balancer` link looks fine but the `PIDs` label is flush against the border

image

Metrics: `Hostname`, `Port`, `Load` button, labels on top of input field boxes are flush to the left, not sure if it should be slightly indented as in the Composer?  `Load` button seems not vertically aligned with the input field boxes

image

Profiler: same as above in Metrics on the PID selector

image

### PR DESCRIPTION
**Pull request by jtary**
@anthonyettinger PTAL

### CODE REVIEW

**Comment by jtary** [comment]
related to #1085

**Comment by anthonyettinger** [comment]
LGTM -- @seanbrookes 

@jtary we need to port whatever changes we made back to the styleguide as that is the source of truth. I see you added a UIDataTable directive. Styleguide should use this too.

**Comment by jtary** [comment]
@anthonyettinger I'll make an update to the style guide to use the data-table directive.

**Comment by anthonyettinger** [comment]
LGTM

**Pull request merged**
