### PR TITLE
remove ng-clipboard and zeroclipboard libraries

### PR DESCRIPTION
**Pull request by anthonyettinger**
- remove all references to ngClipboard
- remove "Copy" button from license page

@seanbrookes PTAL

### CODE REVIEW

**Comment by anthonyettinger** [comment]
test please

**Comment by seanbrookes** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
Now it is failing in the tests:
```
[23:19:01] Starting 'test-client-integration'...
Arc running at http://localhost:9800
Running node_modules/.bin/karma start --single-run --browsers PhantomJS client/test/integration/karma.integration.js
WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket C-meBTxQ4OjQ7_Qd6P_D with id 58164279
ERROR: 'ReferenceError: Can't find variable: require
    at http://localhost:9876/base/client/www/scripts/modules/manager/manager.services.js?e0688f419f087116662910f4ac14b9ecadc8bb2e:169
    at http://localhost:9876/base/client/www/scripts/modules/pm/pm.services.js?e25e56a9c6777ac0a13f1d34585b4d7f7bf2abe7:200
    at http://localhost:9876/base/client/www/scripts/modules/pm/pm.services.js?e25e56a9c6777ac0a13f1d34585b4d7f7bf2abe7:220
    at http://localhost:9876/base/client/www/scripts/modules/pm/pm.module.js?cba5604a6cee2c6f77f509f0223a82b2a14f42d8:38
    at processQueue (http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?95c6c1edba2857fdbab335f994734b9e99e0c81a:13300)
    at http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?95c6c1edba2857fdbab335f994734b9e99e0c81a:13316
    at http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?95c6c1edba2857fdbab335f994734b9e99e0c81a:14555
    at http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?95c6c1edba2857fdbab335f994734b9e99e0c81a:14371
    at http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?95c6c1edba2857fdbab335f994734b9e99e0c81a:14660
    at http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?95c6c1edba2857fdbab335f994734b9e99e0c81a:16408
    at completeOutstandingRequest (http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?95c6c1edba2857fdbab335f994734b9e99e0c81a:4940)
    at http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?95c6c1edba2857fdbab335f994734b9e99e0c81a:5328'
--reset-start--
/mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/client/test/test-server.js:46
      entity.find(function(err, list) {
             ^
TypeError: undefined is not a function
    at /mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/client/test/test-server.js:46:14
    at iterate (/mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/node_modules/async/lib/async.js:146:13)
    at /mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/node_modules/async/lib/async.js:157:25
    at /mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/node_modules/async/lib/async.js:154:25
    at /mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/node_modules/loopback-datasource-juggler/lib/dao.js:1702:7
    at /mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/node_modules/loopback-datasource-juggler/lib/dao.js:1646:9
    at doNotify (/mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
    at doNotify (/mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
    at doNotify (/mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
    at doNotify (/mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
WARN [proxy]: failed to proxy /workspace/api/PackageDefinitions/findOne (socket hang up)
[23:19:07] 'test-client-integration' errored after 6.61 s
[23:19:07] Error: Failed with exit code 1
    at ChildProcess.<anonymous> (/mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/gulpfile.js:312:16)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
[23:19:07] 'test' errored after 12 s
[23:19:07] Error: Failed with exit code 1
    at ChildProcess.<anonymous> (/mnt/jenkins/workspace/strong-arc.pr/cdcdef7b/gulpfile.js:312:16)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
WARN [proxy]: failed to proxy /workspace/api/PackageDefinitions/findOne (socket hang up)
WARN [proxy]: failed to proxy /api/Subscriptions/products (socket hang up)
WARN [proxy]: failed to proxy /scripts/modules/landing/templates/landing.main.html (socket hang up)
WARN [proxy]: failed to proxy /reset (socket hang up)
npm ERR! Test failed.  See above for more details.
```

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
@rmg @ritch I can't figure out what the issue is on this one.

tests fail locally too.

**Comment by rmg** [comment]
@anthonyettinger if you rebase this on to master it should clear up any failures that aren't related to this PR.

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
