### PR TITLE
license v2 refactor

### PR DESCRIPTION
**Pull request by anthonyettinger**
license v2 refactor

- remove auto-renew license logic from router
- add explicity feature license renew calls for metrics and tracing
- add explicity renew button for each feature license on licesning page

@seanbrookes @jtary PTAL

DO NOT MERGE UNTIL AL GIVES THE THUMBS UP!!!

### CODE REVIEW

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
@seanbrookes PTAL

**Comment by seanbrookes** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
