### PR TITLE
add current dir to breadcrumb and delete projects

### PR DESCRIPTION
**Pull request by anthonyettinger**
add ability to delete a project from the project list

add current directory to end of breadcrumb list

### CODE REVIEW

**Comment by anthonyettinger** [comment]
@jtary PTAL

**Comment by anthonyettinger** [comment]
connects to strongloop-internal/scrum-arc#47
connects to strongloop-internal/scrum-arc#43

**Comment by jtary** [comment]
LGTM

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
