### PR TITLE
- upgrade status interaction

### PR DESCRIPTION
**Pull request by seanbrookes**

### CODE REVIEW

**Comment by anthonyettinger** [comment]
LGTM

**Comment by seanbrookes** [comment]
test please

**Comment by seanbrookes** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
test again

**Comment by rmg** [comment]
Resolve the merge conflict and it will build.

**Comment by seanbrookes** [comment]
test please

**Pull request merged**
