### PR TITLE
Revert "Fix squashed  / overlapping chart containers"

### PR DESCRIPTION
**Pull request by anthonyettinger**
This reverts commit eabf6342097e3b4e76153e5dfdbd100214ba5a7a.

### CODE REVIEW

**Comment by anthonyettinger** [comment]
@jtary PTAL

**Comment by jtary** [comment]
LGTM

**Comment by anthonyettinger** [comment]
Test please

**Comment by anthonyettinger** [comment]
test please

**Comment by rmg** [comment]
@slnode test please

**Comment by anthonyettinger** [comment]
test please

**Pull request merged**
