### PR TITLE
Change loopback-explorer to loopback-component-explorer

### PR DESCRIPTION
**Pull request by jtary**
Remove references to loopback-explorer, which is deprecated, and
replace with loopback-component-explorer.

connect to #1642

### CODE REVIEW

**Comment by jtary** [comment]
test please

**Comment by jtary** [comment]
test please

**Comment by jtary** [comment]
test please

**Comment by jtary** [comment]
test please

**Comment by jtary** [comment]
test please

**Comment by jtary** [comment]
test please

**Comment by rmg** [comment]
LGTM :+1:

**Pull request merged**
